.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTPOSTOVERLAYREDISPLAY 3 LOCAL
.Dd
.Sh NAME
.Nm glutPostOverlayRedisplay
.Nd Posts a redispaly against the layer for the current window.
.Sh LIBRARY
OpenGLUT - overlays
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutPostOverlayRedisplay "void"
.Sh DESCRIPTION
For the 
.Bf Li
 current window
.Ef
 , tells OpenGLUT that you
wish to have your OverlayDisplay callback invoked.
.Pp
.Sh CAVEATS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutEstablishOverlay 3
.Xr glutRemoveOverlay 3
.Xr glutUseLayer 3
.Xr glutPostWindowOverlayRedisplay 3
.Xr glutShowOverlay 3
.Xr glutHideOverlay 3
.Xr glutOverlayDisplayFunc 3
.Xr glutPostRedisplay 3
.fl
.sp 3
