.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTMOTIONFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutMotionFunc
.Nd Reports mouse-motion while a button is held.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutMotionFunc "void( *callback )( int x" "int y )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client hook for dragging mouse.
.Sh DESCRIPTION
This function reports the mouse position when the mouse
is dragged starting from within your window.
(``Dragging'' occurs when you press one or more mouse
buttons in one of your OpenGLUT windows, and then
move the mouse around.)
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Events are reported until the mouse button is released, even if the mouse leaves the window.
.Pp
Windows created via glutCreateMenuWindow() always cascade keyboard and mouse events to their parent.
.Pp
.Sh SEE ALSO
.Xr glutMouseFunc 3
.Xr glutPassiveMotion 3
.fl
.sp 3
