.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTHIDEOVERLAY 3 LOCAL
.Dd
.Sh NAME
.Nm glutHideOverlay
.Nd Make an overlay invisible.
.Sh LIBRARY
OpenGLUT - overlays
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutHideOverlay "void"
.Sh DESCRIPTION
Causes a visible overlay to become invisible.
Applies to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutEstablishOverlay 3
.Xr glutRemoveOverlay 3
.Xr glutUseLayer 3
.Xr glutPostOverlayRedisplay 3
.Xr glutPostWindowOverlayRedisplay 3
.Xr glutShowOverlay 3
.fl
.sp 3
