.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTLEAVEGAMEMODE 3 LOCAL
.Dd
.Sh NAME
.Nm glutLeaveGameMode
.Nd Leave game mode, returning to normal desktop mode
.Sh LIBRARY
OpenGLUT - gamemode
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutLeaveGameMode "void"
.Sh DESCRIPTION
.Sh TODO
Documentation
.Pp
.Sh SEE ALSO
.Xr glutGameModeString 3
.Xr glutEnterGameMode 3
.Xr glutLeaveGameMode 3
.Xr glutGameModeGet 3
.fl
.sp 3
