.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTTABLETBUTTONFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutTabletButtonFunc
.Nd Sets a tablet button callback.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutTabletButtonFunc "void( *callback )( int button" "int state" "int x" "int y )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client tablet button hook.
.Sh DESCRIPTION
This function registers a 
.Bf Sy
 callback
.Ef
 by which you receive
reports a tablet button status feature.  Buttons are
reported with 
.Bf Sy
 button
.Ef
 in the range 1 to
glutDeviceGet(
.Bf Sy
 GLUT_NUM_TABLET_BUTTONS).
.Ef
  
.Bf Sy
 state
.Ef
 is either
.Bf Sy
 GLUT_UP
.Ef
 or 
.Bf Sy
 GLUT_DOWN
.Ef
 and 
.Bf Sy
 x
.Ef
 and 
.Bf Sy
 y
.Ef
 are the
tablet coordinate (see glutTabletMotionFunc() for the bounds
of 
.Bf Sy
 x
.Ef
 and 
.Bf Sy
 y).
.Ef
 
.Pp
The callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
OpenGLUT does not implement tablet support.
.Pp
Buttons are 
.Bf Em
 not
.Ef
  pressure-sensitive.
.Pp
.Sh TODO
We might want to add support for this sooner or later. Although a tablet could also be generalized as a mouse. There are relatively cheap AipTek HyperPen tablets, and slightly less cheap Wacom tablets on many store shelves.
.Pp
.Sh SEE ALSO
.Xr glutTabletButtonFunc 3
.Xr glutMouseFunc 3
.fl
.sp 3
