.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTENTRYFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutEntryFunc
.Nd Window mouse entry/leave callback.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutEntryFunc "void( *callback )( int state )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client window-entry hook.
.Sh DESCRIPTION
When the mouse enters or exits a window (or sub-window),
OpenGLUT can report this transition via the Entry
callback.  
.Bf Sy
 state
.Ef
 is one of 
.Bf Sy
 GLUT_LEFT
.Ef
 or
.Bf Sy
 GLUT_ENTERED
.Ef
 respective of whether the mouse
left or entered the window.
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh SEE ALSO
.Xr glutPassiveMotionFunc 3
.fl
.sp 3
