.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTLEAVEMAINLOOP 3 LOCAL
.Dd
.Sh NAME
.Nm glutLeaveMainLoop
.Nd Breaks out of OpenGLUT's glutMainLoop()
.Sh LIBRARY
OpenGLUT - mainloop
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutLeaveMainLoop "void"
.Sh DESCRIPTION
This function allows you to unilaterally tell OpenGLUT
that you are done and wish to exit.  This is useful if
you have also told OpenGLUT to return to you rather than
to call exit() directly.
.Pp
.Sh TODO
Could use longjmp(); see oghTakeActionOnWindowClose(). This would let us terminate the entire loop immediately.
.Pp
.Sh SEE ALSO
.Xr glutMainLoop 3
.Xr exit 3
.fl
.sp 3
