.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTDESTROYMENU 3 LOCAL
.Dd
.Sh NAME
.Nm glutDestroyMenu
.Nd Destroy a menu.
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutDestroyMenu "int menuID"
.Sh PARAMETERS
.Pp
.Bf Em
 menuID
.Ef
    The menu to destroy.
.Sh DESCRIPTION
Destroys a given menu object by its ID.
.Pp
.Sh SEE ALSO
.Xr glutCreateMenu 3
.fl
.sp 3
