.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDTEAPOT 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidTeapot
.Nd Draw a solid teapot.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidTeapot "GLdouble size"
.Sh PARAMETERS
.Pp
.Bf Em
 size
.Ef
        Scale factor.
.Sh DESCRIPTION
Draws the standard Teapot, solid shaded, using OpenGL evaluators.
This is the classic "Utah Teapot" of computer graphics.
The base should lie in the xy-plane with "up" being
along the positive z axis.
.Pp
This is derived from SGI code.  It should also
be the same as the teapot modeled by Martin Newell
in 1975.
.Pp
.Sh SEE ALSO
.Xr glutWireTeapot 3
.fl
.sp 3
