.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDRHOMBICDODECAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidRhombicDodecahedron
.Nd Draw a solid rhombic dodecahedron
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidRhombicDodecahedron "void"
.Sh DESCRIPTION
This function draws a solid-shaded dodecahedron
whose facets are rhombic and
whose vertices are at unit radius.
No facet lies normal to any coordinate axes.
The polyhedron is centered at the origin.
.Pp
.Sh SEE ALSO
.Xr glutWireRhombicDodecahedron 3
.Xr glutWireDodecahedron 3
.Xr glutSolidDodecahedron 3
.fl
.sp 3
