.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDICOSAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidIcosahedron
.Nd Draw a solid icosahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidIcosahedron "void"
.Sh DESCRIPTION
This function draws a regular, solid 20-sided polyhedron
centered at the origin.
The distance from the origin to the vertices is 1.
.Pp
.Sh SEE ALSO
.Xr glutWireIcosahedron 3
.fl
.sp 3
