.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTKEYBOARDFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutKeyboardFunc
.Nd Sets the Keyboard callback for the current window.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutKeyboardFunc "void( * callback )( unsigned char key" "int x" "int y )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client function for keyboard event.
.Sh DESCRIPTION
This callback registration allows you to handle
traditional ASCII keyboard input.  A general rule of
thumb is that if a key has a common ASCII code,
then OpenGLUT assigns that code to the key
and calls the Keyboard 
.Bf Sy
 callback
.Ef
 with the ASCII code in
the 
.Bf Sy
 key
.Ef
 parameter.
For other keys, you must use glutSpecialFunc().
Not all keys can be reported by OpenGLUT.
.Pp
As a convenience, the mouse coordinates, relative
to your window, are also returned.
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
This function is not very international-friendly.
.Pp
Windows created via glutCreateMenuWindow() always cascade keyboard and mouse events to their parent.
.Pp
.Sh SEE ALSO
.Xr glutKeyboardUpFunc 3
.Xr glutSpecialFunc 3
.fl
.sp 3
