.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDCONE 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidCone
.Nd Draw a solid cone.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidCone "GLdouble base" "GLdouble height" "GLint slices" "GLint stacks"
.Sh PARAMETERS
.Pp
.Bf Em
 base
.Ef
       Cone radius at the base in the xy plane.
.Pp
.Bf Em
 height
.Ef
     Height of cone in positive z direction.
.Pp
.Bf Em
 slices
.Ef
     The number of divisions around the z axis. (latitudal)
.Pp
.Bf Em
 stacks
.Ef
     The number of divisions along the z axis. (longitudal)
.Sh DESCRIPTION
The glutSolidCone() function draws a shaded cone
with a base in the xy-plane, oriented in the positive z
direction.
.Pp
.Sh CAVEATS
The number of polygons representing the conical surface is proportional to (slices*stacks).
.Pp
.Sh SEE ALSO
.Xr glutWireCone 3
.fl
.sp 3
