.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTFULLSCREEN 3 LOCAL
.Dd
.Sh NAME
.Nm glutFullScreen
.Nd Resize the current window to cover the entire screen
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutFullScreen "void"
.Sh DESCRIPTION
The glutFullScreen() function resizes the window to cover the
entire screen and hide window decorations such as title bars
and icons.
.Pp
.Sh CAVEATS
The desktop resolution is not affected by a call to glutReshapeWindow() or glutFullScreen().
.Pp
The size of windows is ultimately determined by the windowing system.  Therefore, a fullscreen request by an OpenGLUT application may not necessarily succeed or take immediate effect.
.Pp
Not applicable to offscreen or subwindows.
.Pp
.Sh SEE ALSO
.Xr glutInit 3
.Xr glutInitWindowPosition 3
.Xr glutInitWindowSize 3
.Xr glutGet 3
.Xr glutPositionWindow 3
.Xr glutReshapeWindow 3
.fl
.sp 3
