.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTIGNOREKEYREPEAT 3 LOCAL
.Dd
.Sh NAME
.Nm glutIgnoreKeyRepeat
.Nd Set autorepeat status.
.Sh LIBRARY
OpenGLUT - inputstate
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutIgnoreKeyRepeat "int ignore"
.Sh PARAMETERS
.Pp
.Bf Em
 ignore
.Ef
    Whether to ignore autorepeated keys.
.Sh DESCRIPTION
If 
.Bf Sy
 ignore
.Ef
 is non-zero, then auto-repeat is
disabled for keyboard callbacks for the
.Bf Li
 current window
.Ef
 .
.Pp
.Sh SEE ALSO
.Xr glutSetKeyRepeat 3
.fl
.sp 3
