.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTPOSITIONWINDOW 3 LOCAL
.Dd
.Sh NAME
.Nm glutPositionWindow
.Nd Request to change the position of the current window
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutPositionWindow "int x" "int y"
.Sh PARAMETERS
.Pp
.Bf Em
 x
.Ef
       Requested horizontal position of the current window
.Pp
.Bf Em
 y
.Ef
       Requested vertical position of the current window
.Sh DESCRIPTION
The glutPositionWindow() function requests that the window system
position a top-level or subwindow
relative to the top-left corner.  Subwindows are typically
resized and repositioned in response to window resize events.
.Pp
.Sh CAVEATS
The position of top-level windows is ultimately determined by the windowing system.  Therefore, a position request by an OpenGLUT application may not necessarily succeed.
.Pp
May not take immediate effect; wait for the callback.
.Pp
Not applicable to offscreen windows.
.Pp
.Sh SEE ALSO
.Xr glutInit 3
.Xr glutInitWindowPosition 3
.Xr glutReshapeFunc 3
.Xr  glutCreateSubWindow 3
.fl
.sp 3
