.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIREICOSAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireIcosahedron
.Nd Draw a wireframe icosahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireIcosahedron "void"
.Sh DESCRIPTION
This function draws a regular, solid 20-sided polyhedron
centered at the origin.
The distance from the origin to the vertices is 1.
No facet is normal to any of the 
.Bf Sy
 x,
.Ef
 
.Bf Sy
 y,
.Ef
 or 
.Bf Sy
 z
.Ef
 
axes.
.Pp
.Sh SEE ALSO
.Xr glutSolidIcosahedron 3
.fl
.sp 3
