.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTVIDEORESIZE 3 LOCAL
.Dd
.Sh NAME
.Nm glutVideoResize
.Nd Undocumented, unimplemented.
.Sh LIBRARY
OpenGLUT - videomode
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutVideoResize "int x" "int y" "int w" "int h"
.Sh PARAMETERS
.Pp
.Bf Em
 x
.Ef
    A horizontal position.
.Pp
.Bf Em
 y
.Ef
    A vertical position.
.Pp
.Bf Em
 w
.Ef
    A width.
.Pp
.Bf Em
 h
.Ef
    A height.
.Sh DESCRIPTION
This function is undocumented.  This function is
unimplemeneted (presently).
.Pp
This function appears to allow setting the video
display rectangle to a sub-rectangle of the
hardware buffer.  
.Bf Sy
 x
.Ef
 and 
.Bf Sy
 y
.Ef
 are apparently the
upper left corner, and 
.Bf Sy
 w
.Ef
 and 
.Bf Sy
 h
.Ef
 are the width
and height of the rectangle.
.Pp
It is not clear what should be done if the values
are invalid (negative 
.Bf Sy
 x,
.Ef
 for example).
.Pp
.Sh SEE ALSO
.Xr glutVideoResizeGet 3
.Xr glutSetupVideoResizing 3
.Xr glutStopVideoResizing 3
.Xr glutVideoResize 3
.Xr glutVideoPan 3
.fl
.sp 3
