.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTCLOSEFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutCloseFunc
.Nd Window destruction callback.
.Sh LIBRARY
OpenGLUT - windowcallback
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutCloseFunc "void( *callback )( void )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client window destruction hook.
.Sh DESCRIPTION
When a window is destroyed by user-action in
traditional GLUT, the application terminates.
In freeglut and OpenGLUT, the application can
choose to persist and treat the window close
event as a normal event.  This callback is
how that event is transmitted to the application.
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
This function is 
.Bf Em
 exactly
.Ef
  the same as glutWMCloseFunc(), which has been deprecated. This function should be used instead.
.Pp
.Sh TODO
There needs to be some work to rationalize the behavior when a window is closed.
.Pp
.Sh SEE ALSO
.Xr glutDestroyWindow 3
.fl
.sp 3
