.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTVISIBILITYFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutVisibilityFunc
.Nd Sets the Visibility callback for the current window.
.Sh LIBRARY
OpenGLUT - deprecated
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutVisibilityFunc "void( *callback )( int status )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client hook for visibility changes.
.Sh DESCRIPTION
OpenGLUT may call this function when your window's
visbility status has changed.  
.Bf Sy
 status
.Ef
 can take
on two values: 
.Bf Sy
 GLUT_NOT_VISIBLE
.Ef
 or 
.Bf Sy
 GLUT_VISIBLE
.Ef
 .
If any pixel of your window (including descendants) is
visible, your window is 
.Bf Sy
 GLUT_VISIBLE
.Ef
 .
.Pp
The callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
This is not a polling mechanism.  You are only informed of transitions that OpenGLUT observes while your callback is in place.
.Pp
This function appears to be superceded by glutWindowStatusFunc().
.Pp
This callback is mutually exclusive of glutWindowStatusFunc().
.Pp
.Sh SEE ALSO
.Xr glutWindowStatusFunc 3
.fl
.sp 3
