.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSETWINDOWSTAYONTOP 3 LOCAL
.Dd
.Sh NAME
.Nm glutSetWindowStayOnTop
.Nd Set stay on top mode for current window
.Sh LIBRARY
OpenGLUT - experimental
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSetWindowStayOnTop "int enable"
.Sh PARAMETERS
.Pp
.Bf Em
 enable
.Ef
 Either 
.Bf Sy
 GL_TRUE
.Ef
 or 
.Bf Sy
 GL_FALSE
.Ef
 
.Sh DESCRIPTION
.Sh CAVEATS
Does not work on all window managers.
.Pp
Sends the Icewm style message to all window managers (KDE, twm, blackbox, ratpoison, amiwm, and whatever others you have).  Can we detect Icewm reliably and only send the Icewm formatted message for Icewm?  Possibbly harmless as it stands, but looks wrong.
.Pp
.Sh TODO
Can a glutGet() be defined to tell us whether a window can be made to stay on top?  Or whether a window has (successfully) been marked for staying on top?
.Pp
Should walk the tree of menus and glutPopWindow() (or all windows that are of menu-window type?).
.Pp
Investigate making a workalike variant using glutPopWindow() to mimic the feature where not directly supported.
.Pp
.fl
.sp 3
