.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTINITWINDOWSIZE 3 LOCAL
.Dd
.Sh NAME
.Nm glutInitWindowSize
.Nd Requests future windows to open at a given width/height..
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutInitWindowSize "int width" "int height"
.Sh PARAMETERS
.Pp
.Bf Em
 width
.Ef
    Width of future windows.
.Pp
.Bf Em
 height
.Ef
   Height of future windows.
.Sh DESCRIPTION
This function allows you to request initial dimensions
for future windows.
.Pp
There is a callback function to inform you of the new
window shape (whether initially opened, changed by
your glutReshapeWindow() request, or changed directly
by the user).
.Sh SEE ALSO
.Xr glutReshapeWindow 3
.Xr glutInit 3
.Xr glutInitWindowPosition 3
.Xr glutInitDisplayMode 3
.Xr glutInitDisplayString 3
.Xr glutReshapeFunc 3
.Xr glutGet 3
.fl
.sp 3
