.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTATTACHMENU 3 LOCAL
.Dd
.Sh NAME
.Nm glutAttachMenu
.Nd Attach the current menu to the current window.
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutAttachMenu "int button"
.Sh PARAMETERS
.Pp
.Bf Em
 button
.Ef
    Mouse button to bind to
.Sh DESCRIPTION
Associates the 
.Bf Sy
 button
.Ef
 with the current menu
in the current window.
.Pp
.Sh TODO
Assumes 3 mouse buttons.  (Actually 
.Bf Sy
 FREEGLUT_MAX_MENUS
.Ef
 holds the assumed number of buttons.)  Cannot bind to more buttons.  Will not issue any warnings or errors if the user does not have enough buttons to reach your menu.
.Pp
.Sh SEE ALSO
.Xr glutCreateMenu 3
.Xr glutSetMenu 3
.Xr glutDetachMenu, 3
.fl
.sp 3
