.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIRECUBE 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireCube
.Nd Draw a wireframe cube centered at the origin.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireCube "GLdouble width"
.Sh PARAMETERS
.Pp
.Bf Em
 width
.Ef
       The width, height and depth of the cube.
.Sh DESCRIPTION
The glutWireCube() function draws an axis-aligned wireframe cube
with a specified width, height and depth. The vertices of
the cube are at
(+/- 
.Bf Sy
 width/2,
.Ef
 +/- 
.Bf Sy
 width/2,
.Ef
 +/- 
.Bf Sy
 width/2),
.Ef
 
so that the cube is centered at the origin.
.Pp
.Sh AUTHORS
Code contributed by Andreas Umbach <marvin@dataway.ch>
.Pp
.Sh SEE ALSO
.Xr glutSolidCube 3
.fl
.sp 3
