.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSHOWOVERLAY 3 LOCAL
.Dd
.Sh NAME
.Nm glutShowOverlay
.Nd Make an overlay visible.
.Sh LIBRARY
OpenGLUT - overlays
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutShowOverlay "void"
.Sh DESCRIPTION
Causes a previously-hidden overlay to become
apparent.  Applies to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutEstablishOverlay 3
.Xr glutRemoveOverlay 3
.Xr glutUseLayer 3
.Xr glutPostOverlayRedisplay 3
.Xr glutPostWindowOverlayRedisplay 3
.Xr glutHideOverlay 3
.fl
.sp 3
