.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDSPHERE 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidSphere
.Nd Draw a solid sphere centered at the origin.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidSphere "GLdouble radius" "GLint slices" "GLint stacks"
.Sh PARAMETERS
.Pp
.Bf Em
 radius
.Ef
        Sphere radius.
.Pp
.Bf Em
 slices
.Ef
        The number of divisions around the z axis. (latitudal)
.Pp
.Bf Em
 stacks
.Ef
        The number of divisions along the z axis. (longitudal)
.Sh DESCRIPTION
The glutSolidSphere() function draws a shaded sphere centered at
the origin.  The surface is created from quadrangles
(except for triangles as degenerate quads at the poles) in a
longitude/latitude pattern.  The equatorial great circle lies
in the xy-plane and is centered on the origin.
.Pp
.Sh CAVEATS
The number of polygons representing the spherical surface is proportional to (slices*stacks).
.Pp
.Sh SEE ALSO
.Xr glutWireSphere 3
.fl
.sp 3
