.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTCOPYCOLORMAP 3 LOCAL
.Dd
.Sh NAME
.Nm glutCopyColormap
.Nd Copies a color map between windows.
.Sh LIBRARY
OpenGLUT - colormap
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutCopyColormap "int window"
.Sh PARAMETERS
.Pp
.Bf Em
 window
.Ef
    The window to copy 
.Bf Li
 to
.Ef
 
.Sh DESCRIPTION
Allows you to copy an entire color map from
one window to another.  This function copies
.Bf Em
 from
.Ef
  the 
.Bf Li
 current window
.Ef
 .  It
copies 
.Bf Em
 to
.Ef
  the indicated 
.Bf Sy
 window.
.Ef
 
Respects the current layer setting.
.Pp
.Sh BUGS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutSetColor 3
.Xr glutGetColor 3
.fl
.sp 3
