.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTMENUDESTROYFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutMenuDestroyFunc
.Nd Destruction callback for menus.
.Sh LIBRARY
OpenGLUT - menucallback
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutMenuDestroyFunc "void( *callback )( void )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client menu destruction hook.
.Sh DESCRIPTION
When a menu is destroyed, OpenGLUT will call this
hook, if defined on that menu.
.Pp
This callback is 
.Bf Em
 not
.Ef
  bound to any window.
.Pp
This callback 
.Bf Em
 is
.Ef
  bound to a specific menu.
.Pp
.Sh CAVEATS
For emphasis, we repeat: This callback does not bind to any window.
.Pp
.Sh TODO
What on Earth is rationale for this feature? Menus should only be destroyed when we ask them to be destroyed, or when their window is destroyed. In the former case, we already know that the menu is being destroyed because we requested it.  In the latter case, it is easy for the client to track that if they care, via window-destruction callbacks.
.Pp
.Sh SEE ALSO
.Xr glutCloseFunc 3
.Xr glutCreateMenu 3
.Xr glutDestroyMenu 3
.fl
.sp 3
