.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSHOWWINDOW 3 LOCAL
.Dd
.Sh NAME
.Nm glutShowWindow
.Nd Request that the <i>current window</i> be visible
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutShowWindow "void"
.Sh DESCRIPTION
glutShowWindow() requests that the window system make
the 
.Bf Li
 current window
.Ef
  visible.
.Pp
This is generally not necessary.  When you create a
window, it will normally become visible.  Unless you specifically
hide it, it will remain visible.  Though visible,
of course, it may be covered by other windows;
that would be an issue for window stacking order not
visibility.
.Pp
When, and if, your window's visibility status changes,
you may find out via a glutWindowStatusFunc() callback.
.Pp
.Sh SEE ALSO
.Xr glutHideWindow 3
.Xr glutPopWindow 3
.Xr glutPushWindow 3
.Xr glutWindowStatusFunc 3
.fl
.sp 3
