.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIRESPHERE 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireSphere
.Nd Draw a wireframe sphere centered at the origin.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireSphere "GLdouble radius" "GLint slices" "GLint stacks"
.Sh PARAMETERS
.Pp
.Bf Em
 radius
.Ef
        Sphere radius.
.Pp
.Bf Em
 slices
.Ef
        The number of divisions around the z axis. (latitudal)
.Pp
.Bf Em
 stacks
.Ef
        The number of divisions along the z axis. (longitudal)
.Sh DESCRIPTION
The glutWireSphere() function draws a wireframe sphere centered
at the origin.
The "equatorial" great circle lies in the xy-plane.
.Pp
.Sh CAVEATS
The number of line segments representing the spherical surface is proportional to (slices*stacks).
.Pp
.Sh SEE ALSO
.Xr glutSolidSphere. 3
.fl
.sp 3
