.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTGETMENU 3 LOCAL
.Dd
.Sh NAME
.Nm glutGetMenu
.Nd Get the current menu ID.
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutGetMenu "void"
.Sh DESCRIPTION
Returns the integer ID of the current menu.
.Pp
.Sh SEE ALSO
.Xr glutSetMenu 3
.fl
.sp 3
