.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTTABLETMOTIONFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutTabletMotionFunc
.Nd Sets a tablet motion callback.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutTabletMotionFunc "void (* callback)( int x" "int y )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client tablet motion hook.
.Sh DESCRIPTION
This function registers a 
.Bf Sy
 callback
.Ef
 by which OpenGLUT
reports a puck or stylus position in the range
of [0, 2000] along the 
.Bf Sy
 x
.Ef
 and 
.Bf Sy
 y
.Ef
 axes.
.Pp
The callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
OpenGLUT does not implement tablet support.
.Pp
This API does not include tilt information.
.Pp
.Sh TODO
We might want to add support for this sooner or later. Although a tablet could also be generalized as a mouse. There are relatively cheap AipTek HyperPen tablets, and slightly less cheap Wacom tablets on many store shelves.
.Pp
.Sh SEE ALSO
.Xr glutTabletButtonFunc 3
.Xr glutMouseFunc 3
.fl
.sp 3
