.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTMOUSEWHEELFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutMouseWheelFunc
.Nd Sets the mouse wheel callback for the current window.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutMouseWheelFunc "void( *callback )( int wheel" "int direction" "int x" "int y )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client hook for mouse wheel events.
.Sh DESCRIPTION
If the mouse wheel is spun over your (sub)window,
OpenGLUT will, in theory, report this via the MouseWheel
callback.  
.Bf Sy
 wheel
.Ef
 is the wheel number, 
.Bf Sy
 direction
.Ef
 
is +/- 1, and 
.Bf Sy
 x
.Ef
 and 
.Bf Sy
 y
.Ef
 are the mouse coordinates.
.Pp
If you do not register a wheel callback, wheel events will
be reported as mouse buttons.
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Due to lack of information about the mouse, it is impossible to implement this correctly on X at this time.  Use of this function limits the portability of your application.  (This feature 
.Bf Em
 does
.Ef
  work on X, just not reliably.)  You are encouraged to use the standard, reliable mouse-button reporting, rather than wheel events.
.Pp
Windows created via glutCreateMenuWindow() always cascade keyboard and mouse events to their parent.
.Pp
.Sh SEE ALSO
.Xr glutMouseFunc 3
.fl
.sp 3
