.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSPACEBALLROTATEFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutSpaceballRotateFunc
.Nd Sets a spaceball rotation callback.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSpaceballRotateFunc "void( *callback )( int x" "int y" "int z )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client spaceball rotation hook.
.Sh DESCRIPTION
This function registers a callback for a spaceball
to report rotation.  A spaceball has six axes of freedom
(three of motion and three of orientation), plus buttons.
The spaceball allows you to rotate a control orientation
+/- 1800 units about each of 3 axes.
.Pp
The callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
OpenGLUT does not implement spaceball support.
.Pp
.Sh SEE ALSO
.Xr glutSpaceballMotionFunc 3
.Xr glutSpaceballButtonFunc, 3
.fl
.sp 3
