.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSETMENU 3 LOCAL
.Dd
.Sh NAME
.Nm glutSetMenu
.Nd Set the current menu ID.
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSetMenu "int menuID"
.Sh PARAMETERS
.Pp
.Bf Em
 menuID
.Ef
    Selected menu
.Sh DESCRIPTION
Set the 
.Bf Li
 current menu
.Ef
  to the specified 
.Bf Sy
 menuID.
.Ef
 
.Pp
.Sh SEE ALSO
.Xr glutGetMenu 3
.fl
.sp 3
