.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTDISPLAYFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutDisplayFunc
.Nd Sets the Display callback for the current window.
.Sh LIBRARY
OpenGLUT - windowcallback
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutDisplayFunc "void( *callback )( void )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client function for normal redisplay event.
.Sh DESCRIPTION
Sets the display callback for the 
.Bf Li
 current window
.Ef
 .
All windows, including subwindows, 
.Bf Em
 must
.Ef
  have
a display callback registered.  OpenGLUT will call
the 
.Bf Sy
 callback
.Ef
 function whenever it thinks that the
window may require updating.
.Pp
This callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Unlike most callbacks, it is illegal to try to disable the display callback by setting it to 
.Bf Sy
 NULL
.Ef
 .
.Pp
Multiple redisplays may be coalesced into a single event for invoking the 
.Bf Sy
 callback
.Ef
 only once.
.Pp
.Sh SEE ALSO
.Xr glutPostRedisplay 3
.Xr glutOverlayDisplayFunc 3
.fl
.sp 3
