.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTGETMENUDATA 3 LOCAL
.Dd
.Sh NAME
.Nm glutGetMenuData
.Nd Retrieve menu user data pointer
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutGetMenuData "void"
.Sh DESCRIPTION
Retrieve a previously stored user
data pointer from the current menu.
.Pp
.Sh SEE ALSO
.Xr glutSetMenuData 3
.fl
.sp 3
