.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTGETPROCADDRESS 3 LOCAL
.Dd
.Sh NAME
.Nm glutGetProcAddress
.Nd Determine if an OpenGLUT feature or extension is available.
.Sh LIBRARY
OpenGLUT - openglut
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutGetProcAddress "const char *procName"
.Sh PARAMETERS
.Pp
.Bf Em
 procName
.Ef
    Procedure name.
.Sh DESCRIPTION
Given a function name, searches for the function
(or "procedure", hence "Proc") in
internal tables.  If the function is found, a pointer
to the function is returned.  If the function is not
found, 
.Bf Sy
 NULL
.Ef
 is returned.
.Pp
In addition to an internal OpenGLUT table, this
function will also consult glX (on X systems) or
wgl (on WIN32 and WINCE), if the OpenGLUT tables
do not have the requested function.  It should
return any OpenGL, glX, or wgl function if those
functions are available.
.Pp
.Sh CAVEATS
The code makes no effort towards efficiency. It is advised that you cache the pointer retrieved from this function if you need a certain function repeatedly.
.Pp
.Sh SEE ALSO
.Xr glXGetProcAddress 3
.Xr wglGetProcAddress 3
.fl
.sp 3
