.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTTIMERFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutTimerFunc
.Nd Sets the Timer callback for the current window.
.Sh LIBRARY
OpenGLUT - idletimer
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutTimerFunc "unsigned int msec" "void( *callback )( int data )" "int data"
.Sh PARAMETERS
.Pp
.Bf Em
 msec
.Ef
        Milliseconds till invocation.
.Pp
.Bf Em
 callback
.Ef
    Client function for timer event.
.Pp
.Bf Em
 data
.Ef
        Arbitrary data; passed to 
.Bf Sy
 callback
.Ef
 .
.Sh DESCRIPTION
After 
.Bf Em
 at least
.Ef
  
.Bf Sy
 msec
.Ef
 milliseconds,
OpenGLUT will call 
.Bf Sy
 callback
.Ef
 , passing in your
user-supplied 
.Bf Sy
 data
.Ef
 parameter.  OpenGLUT will
call your function only once.
.Pp
This callback is 
.Bf Em
 not
.Ef
  bound to any window.
.Pp
.Sh CAVEATS
Unlike most other callbacks, timers only occur once.
.Pp
Unlike most other callbacks, you cannot deregister a timer callback.
.Pp
Unlike most other callbacks, you can register an arbitrary number of timers.
.Pp
.Sh SEE ALSO
.Xr glutIdleFunc 3
.Xr glutMainLoop 3
.Xr glutMainLoopEvent 3
.fl
.sp 3
