.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSETCOLOR 3 LOCAL
.Dd
.Sh NAME
.Nm glutSetColor
.Nd Sets an indexed color-mode entry.
.Sh LIBRARY
OpenGLUT - colormap
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSetColor "int nColor" "GLfloat red" "GLfloat green" "GLfloat blue"
.Sh PARAMETERS
.Pp
.Bf Em
 nColor
.Ef
    The palette entry to change.
.Pp
.Bf Em
 red
.Ef
       New red value for palette entry.
.Pp
.Bf Em
 green
.Ef
     New green value for palette entry.
.Pp
.Bf Em
 blue
.Ef
      New blue value for palette entry.
.Sh DESCRIPTION
glutSetCursor() allows you to set individual color-map entries
in a 
.Bf Sy
 GLUT_INDEX
.Ef
 type of display.  Respects the
current overlay setting.
.Pp
.Sh BUGS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutGetColor 3
.Xr glutCopyColorMap 3
.fl
.sp 3
