.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTBITMAPWIDTH 3 LOCAL
.Dd
.Sh NAME
.Nm glutBitmapWidth
.Nd Return the width of a bitmapped character, in pixels.
.Sh LIBRARY
OpenGLUT - bitmapfont
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutBitmapWidth "void *font" "int character"
.Sh PARAMETERS
.Pp
.Bf Em
 font
.Ef
      A bitmapped font identifier.
.Pp
.Bf Em
 character
.Ef
 A character code.
.Sh DESCRIPTION
Returns the horizontal OpenGL raster position
offset for a 
.Bf Sy
 character
.Ef
 in a bitmapped 
.Bf Sy
 font.
.Ef
 
.Pp
It is also an upper bound on the width of the bitmapped glyph
for 
.Bf Sy
 character,
.Ef
 though not all letters will use their full
width, especially fixed-width fonts.
.Pp
Returns 0 if the 
.Bf Sy
 character
.Ef
 is out of the inclusive
range [0,255] or if the 
.Bf Sy
 font
.Ef
 is invalid.
.Pp
.Sh CAVEATS
In GLUT, some glyphs could render to the left of the starting position, in some fonts.  OpenGLUT's fonts all position all of their glyphs to start at, or to the right of, the initial position.
.Pp
.Sh SEE ALSO
.Xr glutBitmapCharacter 3
.Xr glutBitmapLength 3
.Xr glutBitmapHeight 3
.Xr glutStrokeWidth 3
.fl
.sp 3
