.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTCREATEWINDOW 3 LOCAL
.Dd
.Sh NAME
.Nm glutCreateWindow
.Nd Create a new top-level window
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutCreateWindow "const char* title"
.Sh PARAMETERS
.Pp
.Bf Em
 title
.Ef
      Title for created window
.Sh DESCRIPTION
This function sends a request for a window to be constructed.
OpenGLUT immediately constructs a data structure to track further
events with the window, on the theory that eventually the window
manager will get back to us with a real window.  This allows us
to begin registering callbacks immediately.
.Pp
In fact, you 
.Bf Em
 must
.Ef
  register a display callback via
glutDisplayFunc() before you enter glutMainLoop().
.Pp
For onscreen windows, you should not depend upon the window
concretely existing or being visibile until you are told
that it exists and is visible via a registered callback.
.Pp
The return value is an 
.Bf Sy
 int.
.Ef
  It should be positive for
valid windows or 0 if failure occurred for some reason
(Though traditional GLUT tends to bail out and abort
rather than returning errors.)  The integer is your
.Bf Li
 window id
.Ef
 .  Old GLUT promises that these integers
are ``small''; we do not reuse old 
.Bf Li
 id
.Ef
 s, but do
produce them sequentially.
.Pp
You can change the title later via glutSetWindowTitle().
.Pp
.Sh SEE ALSO
.Xr glutDestroyWindow 3
.Xr glutCreateSubWindow 3
.Xr glutSetWindowTitle 3
.Xr glutCreateMenuWindow 3
.fl
.sp 3
