.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDDODECAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidDodecahedron
.Nd Draw a solid dodecahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidDodecahedron "void"
.Sh DESCRIPTION
This function draws a regular, solid, 12-sided polyhedron
centered at the origin.
The distance from the origin to the vertices is
sqrt(3).
The facets are pentagons.
.Pp
.Sh SEE ALSO
.Xr glutWireDodecahedron 3
.Xr glutSolidRhombicDodecahedron 3
.Xr glutWireRhombicDodecahedron 3
.fl
.sp 3
