.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDTETRAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidTetrahedron
.Nd Draw a solid tetrahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidTetrahedron "void"
.Sh DESCRIPTION
This function draws a regular, solid 4-sided polyhedron
centered at the origin.
The distance from the origin to the vertices is 1.
.Pp
.Sh TODO
See todo-list on glutWireTetrahedron().
.Pp
.Sh SEE ALSO
.Xr glutWireTetrahedron 3
.fl
.sp 3
