.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTBITMAPSTRING 3 LOCAL
.Dd
.Sh NAME
.Nm glutBitmapString
.Nd Draw a string of bitmapped characters
.Sh LIBRARY
OpenGLUT - bitmapfont
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutBitmapString "void *font" "const unsigned char *string"
.Sh PARAMETERS
.Pp
.Bf Em
 font
.Ef
    A bitmapped font identifier.
.Pp
.Bf Em
 string
.Ef
  A NUL-terminated ASCII string.
.Sh DESCRIPTION
Draw a 
.Bf Sy
 string
.Ef
 the current OpenGL raster position
using a bitmapped 
.Bf Sy
 font.
.Ef
  The raster position is advanced
by the width of the string.
.Pp
The starting raster position is used as
the left margin for multi-line strings.
Each newline character repositions the raster
position at the beginning of the next line.
.Pp
Nothing is drawn, and the raster position is unaffected when
either:
 - 
.Bf Sy
 font
.Ef
 is not a valid OpenGLUT bitmap font
 - 
.Bf Sy
 string
.Ef
 is an empty string or NULL pointer
 - The current OpenGL raster position is invalid
.Pp
.Sh SEE ALSO
.Xr glRasterPos 3
.Xr glutBitmapCharacter 3
.fl
.sp 3
