.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSETWINDOWDATA 3 LOCAL
.Dd
.Sh NAME
.Nm glutSetWindowData
.Nd Set the user data for the current window
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSetWindowData "void* data"
.Sh PARAMETERS
.Pp
.Bf Em
 data
.Ef
    Arbitrary client-supplied pointer.
.Sh DESCRIPTION
This associates an arbitrary 
.Bf Sy
 void*
.Ef
 value with the
.Bf Li
 current window
.Ef
 .  This is especially useful
in client-side callbacks that service many windows, if
the client needs to know more about the window than
OpenGLUT normally will provide.
.Pp
.Sh SEE ALSO
.Xr glutGetWindowData 3
.fl
.sp 3
