.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSETKEYREPEAT 3 LOCAL
.Dd
.Sh NAME
.Nm glutSetKeyRepeat
.Nd Sets autorepeat behavior for all OpenGLUT windows.
.Sh LIBRARY
OpenGLUT - inputstate
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSetKeyRepeat "int repeatMode"
.Sh PARAMETERS
.Pp
.Bf Em
 repeatMode
.Ef
    On, Off or Default.
.Sh DESCRIPTION
glutSetKeyRepeat() is similar to glutIgnoreKeyRepeat()
but sets the behavior
for OpenGLUT in general, rather than for a particular
window.  The options for 
.Bf Sy
 repeatMode
.Ef
 are:
.Pp
 - 
.Bf Sy
 GLUT_KEY_REPEAT_OFF
.Ef
     
.br
Turn off repeat for all windows.
 - 
.Bf Sy
 GLUT_KEY_REPEAT_ON
.Ef
      
.br
Turn on repeat for all windows.
 - 
.Bf Sy
 GLUT_KEY_REPEAT_DEFAULT
.Ef
 
.br
Respect the window's setting.
.Pp
.Sh SEE ALSO
.Xr glutIgnoreKeyRepeat 3
.fl
.sp 3
