.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTVIDEORESIZEGET 3 LOCAL
.Dd
.Sh NAME
.Nm glutVideoResizeGet
.Nd Undocumented, unimplemented.
.Sh LIBRARY
OpenGLUT - videomode
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutVideoResizeGet "GLenum eWhat"
.Sh PARAMETERS
.Pp
.Bf Em
 eWhat
.Ef
    An enumerated tag.
.Sh DESCRIPTION
This function is undocumented.  This function is
unimplemeneted (presently).
.Pp
From GLUT 3.7's implementation, the following is a
list of symbols that GLUT 3.7 supported.  These are
not necessarily defined in OpenGLUT at this time,
nor is support presently available for them:
.Pp
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_POSSIBLE
.Ef
 (feature presence)
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_IN_USE
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_X_DELTA
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_Y_DELTA
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_WIDTH_DELTA
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEORESIZE_HEIGHT_DELTA
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_REISZE_X
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_Y
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_WIDTH
.Ef
 
 - 
.Bf Sy
 GLUT_VIDEO_RESIZE_HEIGHT
.Ef
 
.Pp
A -1 should be returned for unimplemented features, and
a warning printed.
.Pp
.Sh SEE ALSO
.Xr glutVideoResizeGet 3
.Xr glutSetupVideoResizing 3
.Xr glutStopVideoResizing 3
.Xr glutVideoResize 3
.Xr glutVideoPan 3
.fl
.sp 3
