.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTINITWINDOWPOSITION 3 LOCAL
.Dd
.Sh NAME
.Nm glutInitWindowPosition
.Nd Requests future windows to open at a given position.
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutInitWindowPosition "int x" "int y"
.Sh PARAMETERS
.Pp
.Bf Em
 x
.Ef
    X coordinate.
.Pp
.Bf Em
 y
.Ef
    Y coordinate.
.Sh DESCRIPTION
This function allows you to request an initial position
for future windows.
.Pp
.Sh SEE ALSO
.Xr glutPositionWindow 3
.Xr glutInit 3
.Xr glutInitWindowSize 3
.Xr glutInitDisplayMode 3
.Xr glutInitDisplayString 3
.Xr glutGet 3
.fl
.sp 3
