.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTBITMAPLENGTH 3 LOCAL
.Dd
.Sh NAME
.Nm glutBitmapLength
.Nd Return the width of a bitmapped string, in pixels.
.Sh LIBRARY
OpenGLUT - bitmapfont
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutBitmapLength "void *font" "const unsigned char *string"
.Sh PARAMETERS
.Pp
.Bf Em
 font
.Ef
    A bitmapped font identifier.
.Pp
.Bf Em
 string
.Ef
  A NUL-terminated ASCII string.
.Sh DESCRIPTION
Returns the maximum horizontal OpenGL raster position
offset for a 
.Bf Sy
 string
.Ef
 in a bitmapped 
.Bf Sy
 font.
.Ef
 
.Pp
As with glutBitmapString(), newlines are taken into
consideration.
.Pp
Returns 0 if the 
.Bf Sy
 font
.Ef
 is invalid or if the
.Bf Sy
 string
.Ef
 is empty or 
.Bf Sy
 NULL.
.Ef
 
.Pp
.Sh SEE ALSO
.Xr glutBitmapString 3
.Xr glutBitmapWidth 3
.Xr glutBitmapHeight 3
.Xr glutStrokeLength 3
.fl
.sp 3
