.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTBITMAPHEIGHT 3 LOCAL
.Dd
.Sh NAME
.Nm glutBitmapHeight
.Nd Return the height of a given font, in pixels.
.Sh LIBRARY
OpenGLUT - bitmapfont
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutBitmapHeight "void *font"
.Sh PARAMETERS
.Pp
.Bf Em
 font
.Ef
    A bitmapped font identifier.
.Sh DESCRIPTION
Return the line-to-line vertical spacing (in pixels)
between lines of a bitmapped 
.Bf Sy
 font.
.Ef
 
.Pp
Returns 0 if 
.Bf Sy
 font
.Ef
 is invalid.
.Pp
.Sh CAVEATS
Does 
.Bf Li
 not
.Ef
  report the height used by individual characters.  This may limit its usefulness.  (Compare with other font-metric queries.)
.Pp
.Sh TODO
We have discussed adding a "font descender" query. We should go ahead and do it.
.Pp
.Sh SEE ALSO
.Xr glutBitmapCharacter 3
.Xr glutBitmapString 3
.Xr glutBitmapWidth 3
.Xr glutBitmapLength 3
.Xr glutStrokeHeight 3
.fl
.sp 3
