.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTGETMODIFIERS 3 LOCAL
.Dd
.Sh NAME
.Nm glutGetModifiers
.Nd Returns the status of Alt, Shift, and Ctrl keys.
.Sh LIBRARY
OpenGLUT - inputstate
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutGetModifiers "void"
.Sh DESCRIPTION
According to which, if any, modifier keys are held,
the return value is the logical 
.Bf Sy
 OR
.Ef
 combination
of any of the following symbolic bitmasks:
.Pp
 - 
.Bf Sy
 GLUT_ACTIVE_SHIFT
.Ef
 
 - 
.Bf Sy
 GLUT_ACTIVE_CTRL
.Ef
 
 - 
.Bf Sy
 GLUT_ACTIVE_ALT
.Ef
 
.Pp
E.g., if the shift key is held, and no other modifier
keys are held, this function will return 
.Bf Sy
 GLUT_ACTIVE_SHIFT.
.Ef
 
.Pp
.Sh BUGS
Complains if not invoked by a client callback.
.Pp
Does not differentiate between the left and right forms of the modifiers.
.Pp
.Sh SEE ALSO
.Xr glutSetOption 3
.Xr glutGet 3
.Xr glutDeviceGet 3
.Xr glutLayerGet 3
.fl
.sp 3
