.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTBITMAPCHARACTER 3 LOCAL
.Dd
.Sh NAME
.Nm glutBitmapCharacter
.Nd Draw a bitmapped character
.Sh LIBRARY
OpenGLUT - bitmapfont
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutBitmapCharacter "void *font" "int character"
.Sh PARAMETERS
.Pp
.Bf Em
 font
.Ef
      A bitmapped font identifier.
.Pp
.Bf Em
 character
.Ef
 A character code.
.Sh DESCRIPTION
Draw a 
.Bf Sy
 character
.Ef
 at the current OpenGL raster position
using a bitmapped 
.Bf Sy
 font.
.Ef
  The raster position is advanced
by the width of the character.
.Pp
Nothing is drawn, and the raster position is unaffected when
either:
 - 
.Bf Sy
 character
.Ef
 is out of range
 - 
.Bf Sy
 font
.Ef
 is not a valid OpenGLUT bitmap font
 - The current OpenGL raster position is invalid
.Pp
.Sh CAVEATS
glutBitmapString() is generally more efficient for strings of characters.
.Pp
.Sh SEE ALSO
.Xr glRasterPos 3
.Xr glutBitmapString 3
.Xr glutBitmapWidth 3
.Xr glutBitmapHeight 3
.Xr glutStrokeCharacter 3
.fl
.sp 3
