.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSPACEBALLBUTTONFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutSpaceballButtonFunc
.Nd Sets a spaceball button callback.
.Sh LIBRARY
OpenGLUT - input
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSpaceballButtonFunc "void( *callback )( int button" "int state )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client spaceball button hook.
.Sh DESCRIPTION
This function registers a callback for a spaceball
to report buttons.  A spaceball has six axes of freedom
(three of motion and three of orientation), plus buttons.
The spaceball has glutDeviceGet(
.Bf Sy
 GLUT_NUM_SPACEBALL_BUTTONS)
.Ef
 
and numbers them from 1.  Button state is either
.Bf Sy
 GLUT_UP
.Ef
 or 
.Bf Sy
 GLUT_DOWN.
.Ef
 
.Pp
The callback is bound to the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
OpenGLUT does not implement spaceball support.
.Pp
In contrast, mouse buttons are numbered from 0 in the GLUT API.  This is a wrinkle.
.Pp
.Sh SEE ALSO
.Xr glutSpaceballRotateFunc 3
.Xr glutSpaceballMotiononFunc, 3
.fl
.sp 3
