.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDTORUS 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidTorus
.Nd Draw a solid torus.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidTorus "GLdouble dInnerRadius" "GLdouble dOuterRadius" "GLint nSides" "GLint nRings"
.Sh PARAMETERS
.Pp
.Bf Em
 dInnerRadius
.Ef
    Radius of ``tube''
.Pp
.Bf Em
 dOuterRadius
.Ef
    Radius of ``path''
.Pp
.Bf Em
 nSides
.Ef
          Facets around ``tube''
.Pp
.Bf Em
 nRings
.Ef
          Joints along ``path''
.Sh DESCRIPTION
This function effectively wraps a cylinder with 
.Bf Sy
 nSides
.Ef
 slats
and bends it at 
.Bf Sy
 nRings
.Ef
 facets around a circular
path, forming a torus, or ``donut''.  The center is
at the origin and the ``path'' rings around the
z axis.
.Pp
The torus parameters can be explored interactively
with the OpenGLUT shapes demo.
.Pp
.Sh CAVEATS
.Bf Sy
 dInnerRadius
.Ef
 and 
.Bf Sy
 dOuterRadius
.Ef
 are 
.Bf Em
 not
.Ef
  analogous to similar measurements of an anulus.
.Pp
.Sh SEE ALSO
.Xr glutWireTorus 3
.fl
.sp 3
