.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTMENUSTATEFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutMenuStateFunc
.Nd Deprecated variant of glutMenuStatusFunc()
.Sh LIBRARY
OpenGLUT - deprecated
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutMenuStateFunc "void( *callback )( int status )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client menu status hook.
.Sh DESCRIPTION
Broadly, OpenGLUT operates in two modes.  At any
given time, it is either in menu mode (with a popup
menu display, possibly with subitems) or it is
not.
.Pp
When moving from non-menu to menu status,
.Bf Sy
 callback
.Ef
 (if defined) will be called with
.Bf Sy
 GLUT_MENU_IN_USE
.Ef
 .  Conversely, when moving
from menu to non-menu status,
.Bf Sy
 callback
.Ef
 (if defined) will be called with
.Bf Sy
 GLUT_MENU_NOT_IN_USE
.Ef
 .
.Pp
This callback is bound to 
.Bf Em
 both
.Ef
  the
.Bf Li
 current window
.Ef
  and
the 
.Bf Li
 current menu
.Ef
 .
.Pp
.Sh CAVEATS
Obsolete.  Depcreated.
.Pp
.Sh BUGS
Your callback is not actually called presently.
.Pp
.Sh SEE ALSO
.Xr glutMenuStatusFunc 3
.fl
.sp 3
