.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTREMOVEOVERLAY 3 LOCAL
.Dd
.Sh NAME
.Nm glutRemoveOverlay
.Nd Removes an overlay.
.Sh LIBRARY
OpenGLUT - overlays
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutRemoveOverlay "void"
.Sh DESCRIPTION
Removes the overlay associated with the 
.Bf Li
 current window
.Ef
 .
.Pp
.Sh CAVEATS
Unimplemented.
.Pp
.Sh SEE ALSO
.Xr glutEstablishOverlay 3
.Xr glutUseLayer 3
.Xr glutPostOverlayRedisplay 3
.Xr glutPostWindowOverlayRedisplay 3
.Xr glutShowOverlay 3
.Xr glutHideOverlay 3
.fl
.sp 3
