.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSOLIDOCTAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutSolidOctahedron
.Nd Draw a solid octahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutSolidOctahedron "void"
.Sh DESCRIPTION
This function draws a regular, solid 8-sided polyhedron
centered at the origin.
The vertices are at
(+/-1, 0, 0),
(0, +/-1, 0),
(0, 0, +/-1).
.Pp
.Sh CAVEATS
We visit the same vertices the same number of times as in the wire octahedron, but the order is different.
.Pp
.Sh SEE ALSO
.Xr glutWireOctahedron 3
.fl
.sp 3
