.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTSTOPVIDEORESIZING 3 LOCAL
.Dd
.Sh NAME
.Nm glutStopVideoResizing
.Nd Undocumented, unimplemented.
.Sh LIBRARY
OpenGLUT - videomode
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutStopVideoResizing "void"
.Sh DESCRIPTION
This function is undocumented.  This function is
unimplemeneted (presently).
.Pp
.Sh SEE ALSO
.Xr glutVideoResizeGet 3
.Xr glutSetupVideoResizing 3
.Xr glutStopVideoResizing 3
.Xr glutVideoResize 3
.Xr glutVideoPan 3
.fl
.sp 3
