.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIREDODECAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireDodecahedron
.Nd Draw a wireframe dodecahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireDodecahedron "void"
.Sh DESCRIPTION
This function draws a regular, wireframe 12-sided polyhedron
centered at the origin.
The distance from the origin to the vertices is
sqrt(3).
The facets are pentagons.
No facet is normal any of the 
.Bf Sy
 x,
.Ef
 
.Bf Sy
 y,
.Ef
 or 
.Bf Sy
 z
.Ef
 
axes.
.Pp
.Sh SEE ALSO
.Xr glutSolidDodecahedron 3
.Xr glutWireRhombicDodecahedron 3
.Xr glutSolidRhombicDodecahedron 3
.fl
.sp 3
