.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWMCLOSEFUNC 3 LOCAL
.Dd
.Sh NAME
.Nm glutWMCloseFunc
.Nd Window destruction callback.
.Sh LIBRARY
OpenGLUT - deprecated
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWMCloseFunc "void( *callback )( void )"
.Sh PARAMETERS
.Pp
.Bf Em
 callback
.Ef
    Client window destruction hook.
.Sh DESCRIPTION
.Pp
.Sh SEE ALSO
.Xr glutCloseFunc 3
.fl
.sp 3
