.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTCHANGETOMENUENTRY 3 LOCAL
.Dd
.Sh NAME
.Nm glutChangeToMenuEntry
.Nd Replace a menu entry with an item.
.Sh LIBRARY
OpenGLUT - menus
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutChangeToMenuEntry "int item" "const char *label" "int value"
.Sh PARAMETERS
.Pp
.Bf Em
 item
.Ef
    Integer position down the list
.Pp
.Bf Em
 label
.Ef
   Menu item text
.Pp
.Bf Em
 value
.Ef
   Menu item callback value
.Sh DESCRIPTION
Walks the list of the menu items and replaces
the numbered 
.Bf Sy
 item
.Ef
 in the list with the
given definition.  Except that it replaces a
pre-existing 
.Bf Sy
 item,
.Ef
 this function is much like
glutAddMenuEntry().
.Pp
.Sh SEE ALSO
.Xr glutAddMenuEntry 3
.Xr glutAddSubMenu 3
.Xr glutChangeToSubMenu 3
.Xr glutRemoveMenuItem 3
.fl
.sp 3
