.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTGAMEMODESTRING 3 LOCAL
.Dd
.Sh NAME
.Nm glutGameModeString
.Nd Set the game mode display string
.Sh LIBRARY
OpenGLUT - gamemode
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutGameModeString "const char *string"
.Sh PARAMETERS
.Pp
.Bf Em
 string
.Ef
    A configuration parameter as a string.
.Sh DESCRIPTION
Sets the gamemode status according to an undocumented string.
.Pp
Glancing at old GLUT 3.7, the freeglut codebase that we
inherited does not implement more than a single
GLUT gamemode ``criteria''. It may not even do that
much correctly.
.Pp
In principle, this code lets you set the video dimensions,
rendering depth, and video refresh rate.  In practice,
the combination that you request may be unsupportable
and the target host may even refuse to honor any such
changes.
.Pp
If you use this function but do not set all options,
the following defaults may be substituted for some
values:
.Pp
 - 
.Bf Sy
 width
.Ef
 640
 - 
.Bf Sy
 height
.Ef
 480
 - 
.Bf Sy
 depth
.Ef
 16
 - 
.Bf Sy
 refresh
.Ef
 72
.Pp
.Sh TODO
Documentation
.Pp
.Sh SEE ALSO
.Xr glutGameModeString 3
.Xr glutEnterGameMode 3
.Xr glutLeaveGameMode 3
.Xr glutGameModeGet 3
.fl
.sp 3
