.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIREOCTAHEDRON 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireOctahedron
.Nd Draw a wireframe octahedron.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireOctahedron "void"
.Sh DESCRIPTION
This function draws a regular wireframe 8-sided polyhedron
centered at the origin.
The vertices are at
(+/-1, 0, 0),
(0, +/-1, 0),
(0, 0, +/-1).
.Pp
.Sh CAVEATS
We visit the same vertices the same number of times as for the solid octahedron, but the order is different.
.Pp
Draws every edge twice.
.Pp
The lines have normals, but the normals are from the facets, rather than upon the edge.  If you squint too hard, the lighting on a wireframe octahedron does not look quite right.
.Pp
.Sh TODO
It may be faster (and look better) to draw each edge once, setting the Normal at each edge.  (I don't think that this matters all that much, but a lineloop was proposed for the wire Cube for speed.)
.Pp
.Sh SEE ALSO
.Xr glutSolidOctahedron 3
.fl
.sp 3
