.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTWIRECYLINDER 3 LOCAL
.Dd
.Sh NAME
.Nm glutWireCylinder
.Nd Draw a wireframe cylinder.
.Sh LIBRARY
OpenGLUT - geometry
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutWireCylinder "GLdouble radius" "GLdouble height" "GLint slices" "GLint stacks"
.Sh PARAMETERS
.Pp
.Bf Em
 radius
.Ef
     Radius of cylinder.
.Pp
.Bf Em
 height
.Ef
     Z height.
.Pp
.Bf Em
 slices
.Ef
     Number of divisions around the z axis.
.Pp
.Bf Em
 stacks
.Ef
     Number of divisions along the z axis.
.Sh DESCRIPTION
glutWireCylinder() draws a wireframe of a cylinder,
the center of whose base is at the origin, and
whose axis parallels the z axis.
.Pp
.Sh SEE ALSO
.Xr glutSolidCylinder 3
.fl
.sp 3
