.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTENTERGAMEMODE 3 LOCAL
.Dd
.Sh NAME
.Nm glutEnterGameMode
.Nd Enter game mode
.Sh LIBRARY
OpenGLUT - gamemode
.Sh SYNOPSIS
.In openglut.h
.Ft  int
.Fn glutEnterGameMode "void"
.Sh DESCRIPTION
Any combination of the following may apply:
.Pp
 - Resolution change, possibly to the requested
resolution, possibly to a "nearest match".
 - Refresh frequency change.
 - A window with a drawable area equal to the requested
screen resolution will be opened.
 - The mouse may be restricted to operate within
your window.
.Pp
.Sh CAVEATS
Varies in behavior; X users can disable the resolution change by an OpenGLUT compile-time option.
.Pp
.Sh TODO
Documentation
.Pp
OpenGLUT may be unable to restore the original settings (this has been observed on WIN32).
.Pp
.Sh SEE ALSO
.Xr glutGameModeString 3
.Xr glutEnterGameMode 3
.Xr glutLeaveGameMode 3
.Xr glutGameModeGet 3
.fl
.sp 3
