.\" Copyright 2004, the OpenGLUT contributors
.Dt GLUTDESTROYWINDOW 3 LOCAL
.Dd
.Sh NAME
.Nm glutDestroyWindow
.Nd Destroy a window and associated subwindows
.Sh LIBRARY
OpenGLUT - window
.Sh SYNOPSIS
.In openglut.h
.Ft  void
.Fn glutDestroyWindow "int windowID"
.Sh PARAMETERS
.Pp
.Bf Em
 windowID
.Ef
   Window identifier
.Sh DESCRIPTION
After this function is invoked, the only further event
that may be delivered for your window is the one for its
destruction.  All other events should be discarded.
.Pp
Once a window has been destroyed, further attempts to
use the window named by 
.Bf Sy
 windowID
.Ef
 are undefined.  OpenGLUT generally
tries to be sensible, and should not recycle the dead
.Bf Sy
 windowID,
.Ef
 but you should treat a destroyed window much
like a pointer to deallocated memory and try not to use it.
.Pp
.Sh SEE ALSO
.Xr glutCreateWindow 3
.fl
.sp 3
